services:
  backend:
    build: ./server
    volumes:
      - ./server/src:/app/src
    ports:
      - 4000:4000
  redis:
    image: redis
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=redis
    ports:
      - "8081:8081"
